package config

const (
	SUCCESS                = 200
	SUCCESS_MESSAGE        = "成功"
	Fail                   = 500
	Fail_MESSAGE           = "服务器开小差了"
	CREATE_SUCCESS_MESSAGE = "创建成功"
	REQUEST_FAIL           = 501
	REQUEST_FAIL_MESSAGE   = "获取失败"
	CREATE_FAIL            = 502
	CREATE_FAIL_MESSAGE    = "创建失败"
	DELETE_FAIL            = 503
	DELETE_FAIL_MESSAGE    = "删除失败"
	DELETE_SUCCESS         = 200
	DELETE_SUCCESS_MESSAGE = "删除成功"
	PERPAGE                = 20
)

const (
	// 企业状态
	COMPANY_FRZEE       = 0
	COMPANY_FRZEE_NAME  = "冻结"
	COMPANY_NORMAL      = 1
	COMPANY_NORMAL_NAME = "正常"
	// 企业付款状态
	DEMAND_SALARY_computed      = 0
	DEMAND_SALARY_computed_NAME = "计算完成"
	DEMAND_SALARY_PAIED         = 1
	DEMAND_SALARY_PAIED_NAME    = "已付款"
	DEMAND_SALARY_SENDED        = 2
	DEMAND_SALARY_SENDED_NAME   = "已发放"
	// 企业需求状态标识
	DEMAND_FLAG_DELETE         = -1
	DEMAND_FLAG_DELETE_NAME    = "删除"
	DEMAND_FLAG_SAVE           = 0
	DEMAND_FLAG_SAVE_NAME      = "保存"
	DEMAND_FLAG_VALID          = 1
	DEMAND_FLAG_VALID_NAME     = "有效"
	DEMAND_FLAG_COMPLETED      = 2
	DEMAND_FLAG_COMPLETED_NAME = "满员"
	DEMAND_FLAG_EXPIRED        = 3
	DEMAND_FLAG_EXPIRED_NAME   = "过期"
	// 企业需求状态
	DEMAND_STATUS_UNPUBLISH      = 0
	DEMAND_STATUS_UNPUBLISH_NAME = "未发布"
	DEMAND_STATUS_PUBLISH        = 1
	DEMAND_STATUS_PUBLISH_NAME   = "已发布"
	// 员工状态
	STAFF_ON          = 1
	STAFF_ON_NAME     = "在职"
	STAFF_QUITED      = 2
	STAFF_QUITED_NAME = "离职"
	// 需求限制
	GENDER_UNLIMIT          = 0
	GENDER_UNLIMIT_NAME     = "不限制"
	GENDER_LIMIT_MAN        = 1
	GENDER_LIMIT_MAN_NAME   = "男"
	GENDER_LIMIT_WOMAN      = 2
	GENDER_LIMIT_WOMAN_NAME = "女"
	GENDER_LIMIT_AGE        = "16-60"
	TIME_UNLIMIT            = 1
	TIME_UNLIMIT_NAME       = "不限制时间"
	TIME_LIMIT              = 2
	TIME_LIMIT_NAME         = "时间限制"
	// 报名状态
	DEMAND_USER_ENROLLED          = 1
	DEMAND_USER_ENROLLED_NAME     = "报名成功"
	DEMAND_USER_PASS              = 2
	DEMAND_USER_PASS_NAME         = "通过面试"
	DEMAND_USER_COMPANY_PASS      = 3
	DEMAND_USER_COMPANY_PASS_NAME = "通过企业面试"
	DEMAND_USER_EMPLOYED          = 4
	DEMAND_USER_EMPLOYED_NAME     = "录用"
	DEMAND_USER_QUITTED           = 5
	DEMAND_USER_QUITTED_NAME      = "离职"
	// 需求发布状态
	ISSUE_DEMAND_UNPUBLISH      = 0
	ISSUE_DEMAND_UNPUBLISH_NAME = "未发布"
	ISSUE_DEMAND_PUBLISHED      = 1
	ISSUE_DEMAND_PUBLISHED_NAME = "已发布"
	ISSUE_DEMAND_COMPLETED      = 2
	ISSUE_DEMAND_COMPLETED_NAME = "满员"
	ISSUE_DEMAND_EXPIRED        = 3
	ISSUE_DEMAND_EXPIRED_NAME   = "过期"
	// 员工工资
	STAFF_SALARY_COMPUTED      = 1
	STAFF_SALARY_COMPUTED_NAME = "计算完成"
	STAFF_SALARY_PAIED         = 2
	STAFF_SALARY_PAIED_NAME    = "企业已付款"
	STAFF_SALARY_GRANTED       = 3
	STAFF_SALARY_GRANTED_NAME  = "员工工资已发放"
	// 工种类型
	WORK_TYPE_ONDUTY      = 1
	WORK_TYPE_ONDUTY_NAME = "坐班"
	WORK_TYPE_TIME        = 2
	WORK_TYPE_TIME_NAME   = "计时"
	WORK_TYPE_PIECE       = 3
	WORK_TYPE_PIECE_NAME  = "计件"
)

const (
	DATA_NOT_EXIST         = 404
	DATA_NOT_EXIST_MESSAGE = "数据不存在"
	LOGIN_FAIL             = "login_fail"
	LOGIN_FAIL_CODE        = 2000001
	LOGIN_FAIL_MESSAGE     = "登录失败"
	QUERY_FAIL             = 502
	QUERY_FAIL_MESSAGE     = "查询失败"
)

// 企业状态
var COMPANY_STATUS = map[int]string{
	COMPANY_FRZEE:  COMPANY_FRZEE_NAME,
	COMPANY_NORMAL: COMPANY_FRZEE_NAME,
}

// 企业需求状态标识
var COMPANY_DEMAND_STATUS = map[int]string{
	DEMAND_FLAG_DELETE:    DEMAND_FLAG_DELETE_NAME,
	DEMAND_FLAG_SAVE:      DEMAND_FLAG_SAVE_NAME,
	DEMAND_FLAG_VALID:     DEMAND_FLAG_VALID_NAME,
	DEMAND_FLAG_COMPLETED: DEMAND_FLAG_COMPLETED_NAME,
	DEMAND_FLAG_EXPIRED:   DEMAND_FLAG_EXPIRED_NAME,
}

// 企业薪资状态
var DEMAND_SALARY_STATUS = map[int]string{
	DEMAND_SALARY_computed: DEMAND_SALARY_computed_NAME,
	DEMAND_SALARY_PAIED:    DEMAND_SALARY_PAIED_NAME,
	DEMAND_SALARY_SENDED:   DEMAND_SALARY_SENDED_NAME,
}

// 需求发布状态
var DEMAND_PUBLISH_STATUS = map[int]string{
	DEMAND_STATUS_UNPUBLISH: DEMAND_STATUS_UNPUBLISH_NAME,
	DEMAND_STATUS_PUBLISH:   DEMAND_STATUS_PUBLISH_NAME,
}

// 工资状态
var STAFF_STATUS = map[int]string{
	STAFF_ON:     STAFF_ON_NAME,
	STAFF_QUITED: STAFF_QUITED_NAME,
}

// 需求限制
var DEMAND_LIMIT = map[string]map[int]string{
	"GENDER": {
		GENDER_UNLIMIT:     GENDER_UNLIMIT_NAME,
		GENDER_LIMIT_MAN:   GENDER_LIMIT_MAN_NAME,
		GENDER_LIMIT_WOMAN: GENDER_LIMIT_WOMAN_NAME,
	},
	"TIME": {
		TIME_UNLIMIT: TIME_UNLIMIT_NAME,
		TIME_LIMIT:   TIME_LIMIT_NAME,
	},
}

// 需求报名状态
var DEMAND_STATUS = map[int]string{
	DEMAND_USER_ENROLLED:     DEMAND_USER_ENROLLED_NAME,
	DEMAND_USER_PASS:         DEMAND_USER_PASS_NAME,
	DEMAND_USER_COMPANY_PASS: DEMAND_USER_COMPANY_PASS_NAME,
	DEMAND_USER_EMPLOYED:     DEMAND_USER_EMPLOYED_NAME,
	DEMAND_USER_QUITTED:      DEMAND_USER_QUITTED_NAME,
}

// 需求发布状态
var ISSUE_DEMAND_STATUS = map[int]string{
	ISSUE_DEMAND_UNPUBLISH: ISSUE_DEMAND_UNPUBLISH_NAME,
	ISSUE_DEMAND_PUBLISHED: ISSUE_DEMAND_PUBLISHED_NAME,
	ISSUE_DEMAND_COMPLETED: ISSUE_DEMAND_COMPLETED_NAME,
	ISSUE_DEMAND_EXPIRED:   ISSUE_DEMAND_EXPIRED_NAME,
}

// 员工工资状态
var STAFF_SALARY_STATUS = map[int]string{
	STAFF_SALARY_COMPUTED: STAFF_SALARY_COMPUTED_NAME,
	STAFF_SALARY_PAIED:    STAFF_SALARY_PAIED_NAME,
	STAFF_SALARY_GRANTED:  STAFF_SALARY_GRANTED_NAME,
}

// 工种类型
var WORK_TYPE = map[int]string{
	WORK_TYPE_ONDUTY: WORK_TYPE_ONDUTY_NAME,
	WORK_TYPE_TIME:   WORK_TYPE_TIME_NAME,
	WORK_TYPE_PIECE:  WORK_TYPE_PIECE_NAME,
}
